[project]
name = "etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "prasanna", email = "ID+username@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyiceberg[polars,pyarrow,pyiceberg-core]>=0.12.0,<0.13",
    "polars>=1.44.2,<2",
    "pyarrow>=25.0.1,<26",
]

[project.scripts]
etl = "etl:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "faker>=40.39.0",
    "pyspark>=4.1.3,<4.2",
]
